@baseUrl = http://localhost:3333
@accessToken = {{create_session.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@email.com",
    "password": "secure_password"
}

###
# @name create_session
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "john.doe@email.com",
    "password": "secure_password"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "some title",
    "content": "some content"
}

###
# @name fetch_questions
GET {{baseUrl}}/questions
Authorization: Bearer {{accessToken}}